fix typo, lint, refactor and add clean function
Zombie123456/pydis pull request #1
Opened 2022-07-12 08:52 UTC by YuzhenQin

commit 较乱，如果要 merge 建议 squash 成一个 commit
- 修复 README 内的 typo
- 进行 markdownlint
- 修改了 incr 和 decr，共用一个 _incr
- 修改 keys 函数的逻辑
- 增加 clean 和 clean_force 函数

2022-07-12 13:27 UTC, YuzhenQin commented
关于淘汰数据，我想的是使用一个 _expire 队列，然后可以起一个线程遍历队列清理，其他操作像代码里一样从队头开始清理

2022-07-13 07:13 UTC, Zombie123456 requested changes

2022-07-13 07:13 UTC, Zombie123456 commented on pydis/core.py
> +            if self.ttl(key) != -2:
这里感觉直接 value 的expire比较好，调用 ttl 又会去字典里面额外取一次

2022-07-13 07:13 UTC, Zombie123456 commented on pydis/core.py
> +        if not value.forever_key: self._expire.push((key, value.expire_to))
1、不要将 if 和 内容写到同一行
2、list.push()    'list' object has no attribute 'push' 
3、这个push 按照你的想法的话应该是要放到合适的位置吧，假如 push 存在，可以完成你的想法吗？

2022-07-13 07:13 UTC, Zombie123456 commented on pydis/core.py
> +    """
关于清理的策略，你这样是很好的，
但是每一次set都会遍历这个队列到适合的位置，会比较浪费性能，
这里我们可以随机选取一定数量的设置有过期时间的key出来，如果过期就delete，
取的这个key的数量我们可以进行优化控制
这样取一个择中的方法，逻辑也更简单，配合我们之后会启一个线程来删除key应该就没有问题了

2022-07-13 07:13 UTC, Zombie123456 commented on pydis/core.py
> +        self.clean()
这里的逻辑应该有问题吧，如果已经到期了，但是value 已经拿到了，也会被返回出去

2022-07-13 07:14 UTC, Zombie123456 commented
感谢PR，看了一部分代码，给了一点评论，有问题的话，我们可以讨论， 晚上回去在看看，上班摸鱼。。。

2022-07-13 07:16 UTC, Zombie123456 commented on pydis/core.py
> +    """
而且这样的话，我们的存 有过期时间的key 就可以用 集合，增删改查都是 O(1) 了

2022-07-13 07:47 UTC, YuzhenQin commented on pydis/core.py
> +        if not value.forever_key: self._expire.push((key, value.expire_to))
草，应该是 append

2022-07-13 08:16 UTC, YuzhenQin commented
增加了发版 CI，需要设置 `PYPI_API_TOKEN` secret，在发布 release 的时候会自动上传到 PyPI

2022-07-13 12:15 UTC, YuzhenQin commented on pydis/core.py
> +    """
所以说就是 `有过期时间的 key -> 加入集合 -> 每次随机选一定量检查是否过期` 这样对吗

2022-07-14 01:39 UTC, Zombie123456 commented on pydis/core.py
> +    """
对，我感觉这样会好一点

2022-07-17 03:34 UTC, merged